name: Build and Deploy Web Service

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'web/**'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'web/**'

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  REGISTRY: ${{ secrets.GCP_REGISTRY }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        cd web
        python3 -m pip install -r requirements.txt
    
    - name: Run tests (placeholder)
      run: |
        cd web
        python3 -m pytest || echo "No tests yet"

  deploy-staging:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: staging
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker
      run: gcloud auth configure-docker $REGISTRY
    
    - name: Build Docker image
      run: |
        cd web
        docker build -t $REGISTRY/$PROJECT_ID/stems-web-staging:$GITHUB_SHA .
        docker tag $REGISTRY/$PROJECT_ID/stems-web-staging:$GITHUB_SHA $REGISTRY/$PROJECT_ID/stems-web-staging:latest
    
    - name: Push Docker image
      run: |
        cd web
        docker push $REGISTRY/$PROJECT_ID/stems-web-staging:$GITHUB_SHA
        docker push $REGISTRY/$PROJECT_ID/stems-web-staging:latest
    
    - name: Deploy to Cloud Run (Staging)
      run: |
        gcloud run deploy stems-web-staging \
          --image $REGISTRY/$PROJECT_ID/stems-web-staging:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 3 \
          --set-env-vars ENVIRONMENT=staging
    
    - name: Get staging URL
      id: staging-url
      run: |
        SERVICE_URL=$(gcloud run services describe stems-web-staging --region=$REGION --format='value(status.url)')
        echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT
        echo "Staging service deployed at: $SERVICE_URL"
    
    - name: Test staging deployment
      run: |
        sleep 30  # Wait for deployment to be ready
        curl -f ${{ steps.staging-url.outputs.url }}/ping || exit 1

  deploy-production:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker
      run: gcloud auth configure-docker $REGISTRY
    
    - name: Build Docker image
      run: |
        cd web
        docker build -t $REGISTRY/$PROJECT_ID/stems-web:$GITHUB_SHA .
        docker tag $REGISTRY/$PROJECT_ID/stems-web:$GITHUB_SHA $REGISTRY/$PROJECT_ID/stems-web:latest
    
    - name: Push Docker image
      run: |
        cd web
        docker push $REGISTRY/$PROJECT_ID/stems-web:$GITHUB_SHA
        docker push $REGISTRY/$PROJECT_ID/stems-web:latest
    
    - name: Deploy to Cloud Run (Production)
      run: |
        gcloud run deploy stems-web \
          --image $REGISTRY/$PROJECT_ID/stems-web:$GITHUB_SHA \
          --region $REGION \
          --platform managed \
          --allow-unauthenticated \
          --port 8080 \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars ENVIRONMENT=production
    
    - name: Get production URL
      id: production-url
      run: |
        SERVICE_URL=$(gcloud run services describe stems-web --region=$REGION --format='value(status.url)')
        echo "url=$SERVICE_URL" >> $GITHUB_OUTPUT
        echo "Production service deployed at: $SERVICE_URL"
    
    - name: Test production deployment
      run: |
        sleep 30  # Wait for deployment to be ready
        curl -f ${{ steps.production-url.outputs.url }}/ping || exit 1
